export const ORDER_STATUS_ALLOW = {
  DRAFT: ["AWAITING_DEPOSIT", "CANCELLED"],
  AWAITING_DEPOSIT: ["DEPOSIT_PAID", "CANCELLED"],
  DEPOSIT_PAID: ["MEASUREMENTS_CONFIRMED", "CANCELLED"],
  MEASUREMENTS_CONFIRMED: ["IN_PRODUCTION"],
  IN_PRODUCTION: ["QUALITY_CHECK"],
  QUALITY_CHECK: ["READY_TO_SHIP", "IN_PRODUCTION"],
  READY_TO_SHIP: ["DISPATCHED"],
  DISPATCHED: ["DELIVERED", "DELIVERY_REFUSED"],
  DELIVERED: ["COMPLETED"],
  COMPLETED: [],
  CANCELLED: [],
  REFUND_PENDING: ["REFUNDED"],
  REFUNDED: [],
  DELIVERY_REFUSED: ["WRITE_OFF"],
  WRITE_OFF: [],
} as const;

export type OrderStatus = keyof typeof ORDER_STATUS_ALLOW;

/** Guest checkout transitions use this actor until Step 29 links customers. */
export const CHECKOUT_GUEST_ACTOR_ID =
  "01900001-2345-7890-abcd-ef123456789b";
