/** AUTO-GENERATED — run `npx tsx scripts/generate-sizing-research-seeds.ts` */
import type { CategorySeed } from "../sizing-catalogue";

export const RESEARCH_GARMENT_CATEGORY_SEEDS: readonly CategorySeed[] = [
  {
    key: "KAMEEZ",
    name: "Kameez",
    nameUr: "قمیض",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "SLEEVE_OPENING", "ARMHOLE", "NECK_DEPTH_FRONT", "NECK_DEPTH_BACK", "LENGTH", "SWEEP"],
    sortOrder: 10,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Core eastern shirt/top",
  },
  {
    key: "KURTA",
    name: "Kurta",
    nameUr: "کرتا",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 11,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Women’s kurta/top",
  },
  {
    key: "KURTI",
    name: "Kurti",
    nameUr: "کرتی",
    measurementKeys: ["BUST", "UPPER_WAIST", "HIP", "SHOULDER", "LENGTH"],
    sortOrder: 12,
    productType: "wearable",
    typicalRange: "XS-7XL",
    evidenceStatus: "Measured",
    definition: "Long/short/floor kurti",
  },
  {
    key: "A_LINE_SHIRT",
    name: "A-line Shirt",
    nameUr: "A-line Shirt",
    measurementKeys: ["BUST", "SHOULDER", "LENGTH", "SWEEP"],
    sortOrder: 13,
    productType: "wearable",
    typicalRange: "XS-XL",
    evidenceStatus: "Confirmed",
    definition: "Flared shirt silhouette",
  },
  {
    key: "STRAIGHT_SHIRT",
    name: "Straight Shirt",
    nameUr: "Straight Shirt",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH"],
    sortOrder: 14,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Straight shirt silhouette",
  },
  {
    key: "ANGRAKHA",
    name: "Angrakha",
    nameUr: "Angrakha",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 15,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Wrap/tie-front top/dress",
  },
  {
    key: "TROUSER",
    name: "Trouser",
    nameUr: "ٹراوزر",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "LENGTH", "BOTTOM_OPENING"],
    sortOrder: 16,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Regular trouser",
  },
  {
    key: "SHALWAR",
    name: "Shalwar",
    nameUr: "شلوار",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "LENGTH", "BOTTOM_OPENING"],
    sortOrder: 17,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Traditional lower garment",
  },
  {
    key: "PANT",
    name: "Pant",
    nameUr: "Pant",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "LENGTH", "BOTTOM_OPENING"],
    sortOrder: 18,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Measured",
    definition: "Straight/cigarette/fusion pant",
  },
  {
    key: "PALAZZO",
    name: "Palazzo",
    nameUr: "Palazzo",
    measurementKeys: ["LOWER_WAIST", "LENGTH"],
    sortOrder: 19,
    productType: "wearable",
    typicalRange: "XS-7XL",
    evidenceStatus: "Measured",
    definition: "Wide-leg bottom",
  },
  {
    key: "CULOTTE",
    name: "Culotte",
    nameUr: "Culotte",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "LENGTH", "BOTTOM_OPENING"],
    sortOrder: 20,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Wide cropped bottom",
  },
  {
    key: "CAPRI",
    name: "Capri",
    nameUr: "Capri",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "LENGTH", "BOTTOM_OPENING"],
    sortOrder: 21,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Cropped bottom",
  },
  {
    key: "SKIRT",
    name: "Skirt",
    nameUr: "اسکرٹ",
    measurementKeys: ["WAIST", "HIP", "LENGTH", "SWEEP"],
    sortOrder: 22,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Fusion/Western skirt",
  },
  {
    key: "LEHENGA",
    name: "Lehenga",
    nameUr: "لہنگا",
    measurementKeys: ["BUST", "UPPER_WAIST", "HIP", "LOWER_WAIST", "LENGTH"],
    sortOrder: 23,
    productType: "wearable",
    typicalRange: "XS-7XL",
    evidenceStatus: "Measured",
    definition: "Festive/bridal skirt set",
  },
  {
    key: "GHARARA",
    name: "Gharara",
    nameUr: "Gharara",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "KNEE_ROUND", "LENGTH", "BOTTOM_OPENING"],
    sortOrder: 24,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Festive flared bottom",
  },
  {
    key: "SHARARA",
    name: "Sharara",
    nameUr: "Sharara",
    measurementKeys: ["WAIST", "HIP", "THIGH", "RISE", "LENGTH", "BOTTOM_OPENING", "SWEEP"],
    sortOrder: 25,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Festive flared bottom",
  },
  {
    key: "GOWN",
    name: "Gown",
    nameUr: "گاؤن",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 26,
    productType: "wearable",
    typicalRange: "XXS-XL",
    evidenceStatus: "Confirmed",
    definition: "Formal long dress",
  },
  {
    key: "MAXI_DRESS",
    name: "Maxi Dress",
    nameUr: "Maxi Dress",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 27,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Long dress",
  },
  {
    key: "FROCK",
    name: "Frock",
    nameUr: "Frock",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 28,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Flared dress",
  },
  {
    key: "ANARKALI",
    name: "Anarkali",
    nameUr: "Anarkali",
    measurementKeys: ["BUST", "UPPER_WAIST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 29,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Fitted bodice/flared dress",
  },
  {
    key: "PESHWAAS",
    name: "Peshwaas",
    nameUr: "Peshwaas",
    measurementKeys: ["BUST", "UPPER_WAIST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 30,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Long festive dress",
  },
  {
    key: "KAFTAN",
    name: "Kaftan",
    nameUr: "Kaftan",
    measurementKeys: ["BUST", "HIP", "SHOULDER", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 31,
    productType: "wearable",
    typicalRange: "XS-XXL/Free",
    evidenceStatus: "Proposed",
    definition: "Loose dress/top",
  },
  {
    key: "ABAYA",
    name: "Abaya",
    nameUr: "عبaya",
    measurementKeys: ["BUST", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH", "SWEEP"],
    sortOrder: 32,
    productType: "wearable",
    typicalRange: "S-XL/Free",
    evidenceStatus: "Confirmed",
    definition: "Modest outer dress",
  },
  {
    key: "CAPE",
    name: "Cape",
    nameUr: "Cape",
    measurementKeys: ["SHOULDER", "LENGTH", "SWEEP"],
    sortOrder: 33,
    productType: "wearable",
    typicalRange: "Free/XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Outer layer",
  },
  {
    key: "JACKET",
    name: "Jacket",
    nameUr: "Jacket",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "SLEEVE_LENGTH", "ARMHOLE", "LENGTH"],
    sortOrder: 34,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Layering piece",
  },
  {
    key: "WAISTCOAT",
    name: "Waistcoat",
    nameUr: "Waistcoat",
    measurementKeys: ["BUST", "WAIST", "HIP", "SHOULDER", "ARMHOLE", "LENGTH"],
    sortOrder: 35,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Proposed",
    definition: "Sleeveless layer",
  },
  {
    key: "CO_ORD_SET",
    name: "Co-ord Set",
    nameUr: "Co-ord Set",
    measurementKeys: ["TOP_BUST", "TOP_WAIST", "TOP_HIP", "TOP_LENGTH", "BOTTOM_WAIST", "BOTTOM_HIP", "BOTTOM_RISE", "BOTTOM_LENGTH"],
    sortOrder: 36,
    productType: "set",
    typicalRange: "XS-XXL",
    evidenceStatus: "Confirmed",
    definition: "Matched top and bottom",
  },
  {
    key: "BLOUSE_CHOLI",
    name: "Blouse/Choli",
    nameUr: "Blouse/Choli",
    measurementKeys: ["BUST", "UPPER_WAIST", "WAIST", "SHOULDER", "ARMHOLE", "SLEEVE_LENGTH", "LENGTH"],
    sortOrder: 37,
    productType: "wearable",
    typicalRange: "XS-XXL",
    evidenceStatus: "Measured",
    definition: "Saree/lehenga top",
  },
  {
    key: "SAREE",
    name: "Saree",
    nameUr: "ساری",
    measurementKeys: ["LENGTH", "WIDTH"],
    sortOrder: 38,
    productType: "fabric",
    typicalRange: "One size + blouse",
    evidenceStatus: "Confirmed",
    definition: "Draped fabric",
  },
  {
    key: "DUPATTA",
    name: "Dupatta",
    nameUr: "دوپٹہ",
    measurementKeys: ["LENGTH", "WIDTH"],
    sortOrder: 39,
    productType: "accessory",
    typicalRange: "One size",
    evidenceStatus: "Confirmed",
    definition: "Scarf component",
  },
  {
    key: "SHAWL",
    name: "Shawl",
    nameUr: "شawl",
    measurementKeys: ["LENGTH", "WIDTH"],
    sortOrder: 40,
    productType: "accessory",
    typicalRange: "One size",
    evidenceStatus: "Confirmed",
    definition: "Wrap/accessory",
  },
  {
    key: "UNSTITCHED_1PC",
    name: "Unstitched 1-piece",
    nameUr: "Unstitched 1-piece",
    measurementKeys: ["FABRIC_LENGTH", "FABRIC_WIDTH"],
    sortOrder: 41,
    productType: "fabric",
    typicalRange: "Fabric cut",
    evidenceStatus: "Confirmed",
    definition: "Fabric cut",
  },
  {
    key: "UNSTITCHED_2PC",
    name: "Unstitched 2-piece",
    nameUr: "Unstitched 2-piece",
    measurementKeys: ["SHIRT_FABRIC_LENGTH", "SECOND_FABRIC_LENGTH", "FABRIC_WIDTH"],
    sortOrder: 42,
    productType: "fabric",
    typicalRange: "Fabric cut",
    evidenceStatus: "Confirmed",
    definition: "Shirt+bottom or dupatta",
  },
  {
    key: "UNSTITCHED_3PC",
    name: "Unstitched 3-piece",
    nameUr: "Unstitched 3-piece",
    measurementKeys: ["SHIRT_FABRIC_LENGTH", "BOTTOM_FABRIC_LENGTH", "DUPATTA_LENGTH", "FABRIC_WIDTH"],
    sortOrder: 43,
    productType: "fabric",
    typicalRange: "Fabric cut",
    evidenceStatus: "Confirmed",
    definition: "Shirt+bottom+dupatta",
  }
] as const;
