/** AUTO-GENERATED — run `npx tsx scripts/generate-sizing-research-seeds.ts` */
import type { BodyOrGarment, MeasurementKeyDef } from "../sizing-catalogue";

export const RESEARCH_MEASUREMENT_KEY_DEFS: readonly MeasurementKeyDef[] = [
  {
    key: "ARMHOLE",
    label: "Armhole",
    labelUr: "Armhole",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Armhole — inches unless noted in the size chart.",
  },
  {
    key: "BORDER_HEM",
    label: "Border Hem",
    labelUr: "Border Hem",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Border Hem — inches unless noted in the size chart.",
  },
  {
    key: "BOTTOM_FABRIC_LENGTH",
    label: "Bottom Fabric Length",
    labelUr: "Bottom Fabric Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Bottom Fabric Length — metres (stored as hundredths of a metre).",
  },
  {
    key: "BOTTOM_HIP",
    label: "Bottom Hip",
    labelUr: "Bottom Hip",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Bottom Hip — inches unless noted in the size chart.",
  },
  {
    key: "BOTTOM_LENGTH",
    label: "Bottom Length",
    labelUr: "Bottom Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Bottom Length — inches unless noted in the size chart.",
  },
  {
    key: "BOTTOM_OPENING",
    label: "Bottom Opening",
    labelUr: "Bottom Opening",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Bottom Opening — inches unless noted in the size chart.",
  },
  {
    key: "BOTTOM_RISE",
    label: "Bottom Rise",
    labelUr: "Bottom Rise",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Bottom Rise — inches unless noted in the size chart.",
  },
  {
    key: "BOTTOM_WAIST",
    label: "Bottom Waist",
    labelUr: "Bottom Waist",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Bottom Waist — inches unless noted in the size chart.",
  },
  {
    key: "BUST",
    label: "Bust",
    labelUr: "Bust",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "bust_line",
    helpText: "Bust — inches unless noted in the size chart.",
  },
  {
    key: "CHEST",
    label: "Chest",
    labelUr: "Chest",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "bust_line",
    helpText: "Chest — inches unless noted in the size chart.",
  },
  {
    key: "CROSS_BACK",
    label: "Cross Back",
    labelUr: "Cross Back",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Cross Back — inches unless noted in the size chart.",
  },
  {
    key: "DAMAN",
    label: "Daman",
    labelUr: "Daman",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Daman — inches unless noted in the size chart.",
  },
  {
    key: "DAMAN_SHORT",
    label: "Daman Short",
    labelUr: "Daman Short",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Daman Short — inches unless noted in the size chart.",
  },
  {
    key: "DUPATTA_LENGTH",
    label: "Dupatta Length",
    labelUr: "Dupatta Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Dupatta Length — metres (stored as hundredths of a metre).",
  },
  {
    key: "FABRIC_LENGTH",
    label: "Fabric Length",
    labelUr: "Fabric Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "fabric_edge",
    helpText: "Fabric Length — metres (stored as hundredths of a metre).",
  },
  {
    key: "FABRIC_WIDTH",
    label: "Fabric Width",
    labelUr: "Fabric Width",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "fabric_edge",
    helpText: "Fabric Width — metres (stored as hundredths of a metre).",
  },
  {
    key: "FULL_SHIRT_LENGTH",
    label: "Full Shirt Length",
    labelUr: "Full Shirt Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Full Shirt Length — metres (stored as hundredths of a metre).",
  },
  {
    key: "HIP",
    label: "Hip",
    labelUr: "Hip",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "hip_line",
    helpText: "Hip — inches unless noted in the size chart.",
  },
  {
    key: "KNEE_ROUND",
    label: "Knee Round",
    labelUr: "Knee Round",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Knee Round — inches unless noted in the size chart.",
  },
  {
    key: "LENGTH",
    label: "Length",
    labelUr: "Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "shoulder_line",
    helpText: "Length — inches unless noted in the size chart.",
  },
  {
    key: "LENGTH_FRONT",
    label: "Length Front",
    labelUr: "Length Front",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Length Front — inches unless noted in the size chart.",
  },
  {
    key: "LOWER_WAIST",
    label: "Lower Waist",
    labelUr: "Lower Waist",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Lower Waist — inches unless noted in the size chart.",
  },
  {
    key: "NECK_DEPTH_BACK",
    label: "Neck Depth Back",
    labelUr: "Neck Depth Back",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Neck Depth Back — inches unless noted in the size chart.",
  },
  {
    key: "NECK_DEPTH_FRONT",
    label: "Neck Depth Front",
    labelUr: "Neck Depth Front",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Neck Depth Front — inches unless noted in the size chart.",
  },
  {
    key: "RISE",
    label: "Rise",
    labelUr: "Rise",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Rise — inches unless noted in the size chart.",
  },
  {
    key: "SECOND_FABRIC_LENGTH",
    label: "Second Fabric Length",
    labelUr: "Second Fabric Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Second Fabric Length — metres (stored as hundredths of a metre).",
  },
  {
    key: "SHIRT_FABRIC_LENGTH",
    label: "Shirt Fabric Length",
    labelUr: "Shirt Fabric Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Shirt Fabric Length — metres (stored as hundredths of a metre).",
  },
  {
    key: "SHOULDER",
    label: "Shoulder",
    labelUr: "Shoulder",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "shoulder_line",
    helpText: "Shoulder — inches unless noted in the size chart.",
  },
  {
    key: "SLEEVES",
    label: "Sleeves",
    labelUr: "Sleeves",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Sleeves — inches unless noted in the size chart.",
  },
  {
    key: "SLEEVE_LENGTH",
    label: "Sleeve Length",
    labelUr: "Sleeve Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "shoulder_point",
    helpText: "Sleeve Length — inches unless noted in the size chart.",
  },
  {
    key: "SLEEVE_LONG",
    label: "Sleeve Long",
    labelUr: "Sleeve Long",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Sleeve Long — inches unless noted in the size chart.",
  },
  {
    key: "SLEEVE_OPENING",
    label: "Sleeve Opening",
    labelUr: "Sleeve Opening",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Sleeve Opening — inches unless noted in the size chart.",
  },
  {
    key: "SWEEP",
    label: "Sweep",
    labelUr: "Sweep",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Sweep — inches unless noted in the size chart.",
  },
  {
    key: "THIGH",
    label: "Thigh",
    labelUr: "Thigh",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Thigh — inches unless noted in the size chart.",
  },
  {
    key: "TOP_BUST",
    label: "Top Bust",
    labelUr: "Top Bust",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Top Bust — inches unless noted in the size chart.",
  },
  {
    key: "TOP_HIP",
    label: "Top Hip",
    labelUr: "Top Hip",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Top Hip — inches unless noted in the size chart.",
  },
  {
    key: "TOP_LENGTH",
    label: "Top Length",
    labelUr: "Top Length",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Top Length — inches unless noted in the size chart.",
  },
  {
    key: "TOP_WAIST",
    label: "Top Waist",
    labelUr: "Top Waist",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Top Waist — inches unless noted in the size chart.",
  },
  {
    key: "UPPER_WAIST",
    label: "Upper Waist",
    labelUr: "Upper Waist",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Upper Waist — inches unless noted in the size chart.",
  },
  {
    key: "WAIST",
    label: "Waist",
    labelUr: "Waist",
    bodyOrGarment: "BODY" as BodyOrGarment,
    anchorPoint: "waist_line",
    helpText: "Waist — inches unless noted in the size chart.",
  },
  {
    key: "WIDTH",
    label: "Width",
    labelUr: "Width",
    bodyOrGarment: "GARMENT" as BodyOrGarment,
    anchorPoint: "centre",
    helpText: "Width — inches unless noted in the size chart.",
  }
] as const;
