import { inches } from "@aks/shared";

import type { SwatchTexture } from "./demo-swatch-image";

export type DemoFabricDef = {
  name: string;
  composition: string;
  file: string;
  hex: string;
  texture: SwatchTexture;
  weightGsm: number;
  widthInches: number;
  stretchPercent: number;
  shrinkageAllowance: number;
  drapeClass: "LIGHT" | "MEDIUM" | "HEAVY";
  costPerMeterMinor: number;
  careInstructions: string;
  drapeNotes: string;
  /** Garment types this cloth suits — for admin notes. */
  garmentUse: string;
  /** On-hand metres for seed lot (display metres, not hundredths). */
  lotMetres: number;
  /** Reorder threshold in metres. */
  reorderMetres: number;
};

/** All names must start with Demo — purge by prefix at launch. */
export const DEMO_FABRIC_CATALOG: DemoFabricDef[] = [
  {
    name: "Demo White Jersey",
    composition: "95% cotton, 5% elastane",
    file: "demo-white-jersey.jpg",
    hex: "#F4EEE1",
    texture: "knit",
    weightGsm: 180,
    widthInches: inches(58),
    stretchPercent: 5,
    shrinkageAllowance: inches(0.25),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 85_000,
    careInstructions: "Cold wash; reshape flat to dry.",
    drapeNotes: "Soft knit with gentle stretch.",
    garmentUse: "Relaxed kurtas, soft tops, lounge sets",
    lotMetres: 68,
    reorderMetres: 25,
  },
  {
    name: "Demo Olive Silk",
    composition: "Silk crepe",
    file: "demo-olive-silk.jpg",
    hex: "#6B7355",
    texture: "silk",
    weightGsm: 70,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.25),
    drapeClass: "LIGHT",
    costPerMeterMinor: 420_000,
    careInstructions: "Dry clean only.",
    drapeNotes: "Fluid drape with a muted olive cast.",
    garmentUse: "Drapey shalwar kameez, evening separates",
    lotMetres: 80,
    reorderMetres: 30,
  },
  {
    name: "Demo Russian Silk",
    composition: "Silk twill",
    file: "demo-russian-silk.jpg",
    hex: "#8C2F39",
    texture: "silk",
    weightGsm: 85,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.25),
    drapeClass: "LIGHT",
    costPerMeterMinor: 395_000,
    careInstructions: "Dry clean only.",
    drapeNotes: "Clean fall with a muted madder depth.",
    garmentUse: "Formal kurtas, occasion blouses",
    lotMetres: 40,
    reorderMetres: 45,
  },
  {
    name: "Demo Ivory Lawn",
    composition: "100% cotton lawn",
    file: "demo-ivory-lawn.jpg",
    hex: "#F7F3EA",
    texture: "weave",
    weightGsm: 95,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.5),
    drapeClass: "LIGHT",
    costPerMeterMinor: 72_000,
    careInstructions: "Cold wash; warm iron on reverse.",
    drapeNotes: "Crisp hand, breathable for summer.",
    garmentUse: "Summer kurtas, shirts, dupatta linings",
    lotMetres: 145,
    reorderMetres: 40,
  },
  {
    name: "Demo Bone Poplin",
    composition: "Cotton poplin",
    file: "demo-bone-poplin.jpg",
    hex: "#E8E2D4",
    texture: "weave",
    weightGsm: 120,
    widthInches: inches(58),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.35),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 68_000,
    careInstructions: "Machine wash cold; iron while damp.",
    drapeNotes: "Structured hand for clean shirt lines.",
    garmentUse: "Structured shirts, straight kurtas",
    lotMetres: 92,
    reorderMetres: 35,
  },
  {
    name: "Demo Sand Linen",
    composition: "Linen",
    file: "demo-sand-linen.jpg",
    hex: "#C9B89A",
    texture: "weave",
    weightGsm: 155,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.75),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 115_000,
    careInstructions: "Wash separately; steam to finish.",
    drapeNotes: "Dry hand with natural slub.",
    garmentUse: "Relaxed separates, summer trousers",
    lotMetres: 56,
    reorderMetres: 30,
  },
  {
    name: "Demo Stone Khaddar",
    composition: "Cotton khaddar",
    file: "demo-stone-khaddar.jpg",
    hex: "#9A9488",
    texture: "weave",
    weightGsm: 210,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.5),
    drapeClass: "HEAVY",
    costPerMeterMinor: 98_000,
    careInstructions: "Cold wash; line dry.",
    drapeNotes: "Warm weight for cooler months.",
    garmentUse: "Winter kurtas, straight pants",
    lotMetres: 118,
    reorderMetres: 45,
  },
  {
    name: "Demo Taupe Twill",
    composition: "Cotton twill",
    file: "demo-taupe-twill.jpg",
    hex: "#8A8278",
    texture: "weave",
    weightGsm: 240,
    widthInches: inches(58),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.35),
    drapeClass: "HEAVY",
    costPerMeterMinor: 105_000,
    careInstructions: "Turn inside out; wash cold.",
    drapeNotes: "Diagonal weave holds a trouser crease.",
    garmentUse: "Trousers, tailored bottoms, blazers",
    lotMetres: 74,
    reorderMetres: 35,
  },
  {
    name: "Demo Oyster Voile",
    composition: "Cotton voile",
    file: "demo-oyster-voile.jpg",
    hex: "#DDD5C8",
    texture: "sheer",
    weightGsm: 65,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.25),
    drapeClass: "LIGHT",
    costPerMeterMinor: 62_000,
    careInstructions: "Delicate cycle; do not wring.",
    drapeNotes: "Sheer layer with soft opacity.",
    garmentUse: "Dupattas, layered kurtas, overlays",
    lotMetres: 63,
    reorderMetres: 25,
  },
  {
    name: "Demo Milk Crepe",
    composition: "Poly-viscose crepe",
    file: "demo-milk-crepe.jpg",
    hex: "#F4EEE1",
    texture: "silk",
    weightGsm: 130,
    widthInches: inches(58),
    stretchPercent: 3,
    shrinkageAllowance: inches(0.25),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 88_000,
    careInstructions: "Cold wash; hang to dry.",
    drapeNotes: "Matte crepe with easy drape.",
    garmentUse: "Tunics, soft dresses, wide pants",
    lotMetres: 88,
    reorderMetres: 30,
  },
  {
    name: "Demo Espresso Corduroy",
    composition: "Cotton corduroy",
    file: "demo-espresso-corduroy.jpg",
    hex: "#2B2926",
    texture: "velvet",
    weightGsm: 280,
    widthInches: inches(58),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.5),
    drapeClass: "HEAVY",
    costPerMeterMinor: 135_000,
    careInstructions: "Wash inside out; low tumble or line dry.",
    drapeNotes: "Fine wale with deep colour saturation.",
    garmentUse: "Winter pants, structured jackets",
    lotMetres: 47,
    reorderMetres: 30,
  },
  {
    name: "Demo Soft Olive Chiffon",
    composition: "Poly chiffon",
    file: "demo-soft-olive-chiffon.jpg",
    hex: "#8A9478",
    texture: "sheer",
    weightGsm: 55,
    widthInches: inches(58),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.1),
    drapeClass: "LIGHT",
    costPerMeterMinor: 58_000,
    careInstructions: "Hand wash or delicate bag.",
    drapeNotes: "Floaty overlay with muted olive tone.",
    garmentUse: "Dupattas, evening overlays, sleeves",
    lotMetres: 52,
    reorderMetres: 20,
  },
  {
    name: "Demo Antique Gold Brocade",
    composition: "Viscose brocade",
    file: "demo-antique-gold-brocade.jpg",
    hex: "#B08D4C",
    texture: "silk",
    weightGsm: 220,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.25),
    drapeClass: "HEAVY",
    costPerMeterMinor: 520_000,
    careInstructions: "Dry clean only.",
    drapeNotes: "Jacquard body for festive structure.",
    garmentUse: "Festive kurtas, waistcoats, cuffs",
    lotMetres: 28,
    reorderMetres: 15,
  },
  {
    name: "Demo Tea Rose Georgette",
    composition: "Georgette",
    file: "demo-tea-rose-georgette.jpg",
    hex: "#C4A09A",
    texture: "sheer",
    weightGsm: 60,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.15),
    drapeClass: "LIGHT",
    costPerMeterMinor: 95_000,
    careInstructions: "Delicate wash; steam only.",
    drapeNotes: "Soft crinkle hand for flow.",
    garmentUse: "Dupattas, drapey sleeves, overlays",
    lotMetres: 61,
    reorderMetres: 22,
  },
  {
    name: "Demo Charcoal Denim",
    composition: "Cotton denim",
    file: "demo-charcoal-denim.jpg",
    hex: "#3A3835",
    texture: "weave",
    weightGsm: 320,
    widthInches: inches(58),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.5),
    drapeClass: "HEAVY",
    costPerMeterMinor: 125_000,
    careInstructions: "Wash separately; cold.",
    drapeNotes: "Stable weave for straight cuts.",
    garmentUse: "Denim-style trousers, jackets",
    lotMetres: 85,
    reorderMetres: 40,
  },
  {
    name: "Demo Pearl Satin",
    composition: "Poly satin",
    file: "demo-pearl-satin.jpg",
    hex: "#EDE6DA",
    texture: "silk",
    weightGsm: 110,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.2),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 110_000,
    careInstructions: "Cool iron on reverse; dry clean for best finish.",
    drapeNotes: "Low sheen satin for occasion blouses.",
    garmentUse: "Occasion blouses, lining accents",
    lotMetres: 39,
    reorderMetres: 18,
  },
  {
    name: "Demo Sage Muslin",
    composition: "Cotton muslin",
    file: "demo-sage-muslin.jpg",
    hex: "#9AA590",
    texture: "weave",
    weightGsm: 85,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.35),
    drapeClass: "LIGHT",
    costPerMeterMinor: 55_000,
    careInstructions: "Pre-wash before cutting.",
    drapeNotes: "Soft open weave for linings.",
    garmentUse: "Linings, light summer kurtas",
    lotMetres: 120,
    reorderMetres: 35,
  },
  {
    name: "Demo Blush Jersey",
    composition: "Cotton-modal jersey",
    file: "demo-blush-jersey.jpg",
    hex: "#D4B8AE",
    texture: "knit",
    weightGsm: 175,
    widthInches: inches(60),
    stretchPercent: 8,
    shrinkageAllowance: inches(0.25),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 92_000,
    careInstructions: "Cold wash; flat dry.",
    drapeNotes: "Soft handle with recovery.",
    garmentUse: "Soft tops, relaxed tunics",
    lotMetres: 71,
    reorderMetres: 28,
  },
  {
    name: "Demo Navy Wool Blend",
    composition: "Wool-poly blend",
    file: "demo-navy-wool-blend.jpg",
    hex: "#1B2547",
    texture: "weave",
    weightGsm: 290,
    widthInches: inches(58),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.35),
    drapeClass: "HEAVY",
    costPerMeterMinor: 245_000,
    careInstructions: "Dry clean recommended.",
    drapeNotes: "Compact face for outer layers.",
    garmentUse: "Coats, structured blazers",
    lotMetres: 34,
    reorderMetres: 20,
  },
  {
    name: "Demo Cream Organza",
    composition: "Poly organza",
    file: "demo-cream-organza.jpg",
    hex: "#F0E8DA",
    texture: "sheer",
    weightGsm: 45,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.1),
    drapeClass: "LIGHT",
    costPerMeterMinor: 78_000,
    careInstructions: "Steam; avoid heavy iron pressure.",
    drapeNotes: "Crisp sheer for volume.",
    garmentUse: "Festive dupattas, sleeve inserts",
    lotMetres: 44,
    reorderMetres: 18,
  },
  {
    name: "Demo Rust Linen Blend",
    composition: "Linen-cotton blend",
    file: "demo-rust-linen-blend.jpg",
    hex: "#9E6B55",
    texture: "weave",
    weightGsm: 165,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.6),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 102_000,
    careInstructions: "Wash before make; steam finish.",
    drapeNotes: "Relaxed slub with warm rust cast.",
    garmentUse: "Casual kurtas, summer sets",
    lotMetres: 66,
    reorderMetres: 30,
  },
  {
    name: "Demo Slate Gabardine",
    composition: "Poly gabardine",
    file: "demo-slate-gabardine.jpg",
    hex: "#5C6268",
    texture: "weave",
    weightGsm: 260,
    widthInches: inches(58),
    stretchPercent: 3,
    shrinkageAllowance: inches(0.25),
    drapeClass: "HEAVY",
    costPerMeterMinor: 118_000,
    careInstructions: "Wash cold; press with cloth.",
    drapeNotes: "Tight diagonal for tailored pants.",
    garmentUse: "Tailored trousers, uniforms",
    lotMetres: 58,
    reorderMetres: 32,
  },
  {
    name: "Demo Honey Raw Silk",
    composition: "Raw silk",
    file: "demo-honey-raw-silk.jpg",
    hex: "#C9A86C",
    texture: "silk",
    weightGsm: 90,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.3),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 360_000,
    careInstructions: "Dry clean only.",
    drapeNotes: "Textured slub for signature pieces.",
    garmentUse: "Signature kurtas, occasion sets",
    lotMetres: 31,
    reorderMetres: 15,
  },
  {
    name: "Demo Fog Viscose",
    composition: "Viscose twill",
    file: "demo-fog-viscose.jpg",
    hex: "#B8BFC4",
    texture: "silk",
    weightGsm: 140,
    widthInches: inches(58),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.35),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 96_000,
    careInstructions: "Cold wash; hang dry.",
    drapeNotes: "Fluid twill with cool grey cast.",
    garmentUse: "Drapey dresses, wide-leg pants",
    lotMetres: 77,
    reorderMetres: 30,
  },
  {
    name: "Demo Copper Velvet",
    composition: "Cotton velvet",
    file: "demo-copper-velvet.jpg",
    hex: "#8B5A3C",
    texture: "velvet",
    weightGsm: 310,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.25),
    drapeClass: "HEAVY",
    costPerMeterMinor: 285_000,
    careInstructions: "Dry clean; brush nap upward.",
    drapeNotes: "Short pile with rich depth.",
    garmentUse: "Winter occasion kurtas, jackets",
    lotMetres: 22,
    reorderMetres: 12,
  },
  {
    name: "Demo Pistachio Sateen",
    composition: "Cotton sateen",
    file: "demo-pistachio-sateen.jpg",
    hex: "#A8B89A",
    texture: "silk",
    weightGsm: 145,
    widthInches: inches(58),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.35),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 89_000,
    careInstructions: "Iron on cotton setting.",
    drapeNotes: "Soft lustre for polished kurtas.",
    garmentUse: "Polished kurtas, straight shirts",
    lotMetres: 95,
    reorderMetres: 35,
  },
  {
    name: "Demo Aubergine Silk Blend",
    composition: "Silk-viscose blend",
    file: "demo-aubergine-silk-blend.jpg",
    hex: "#4A3548",
    texture: "silk",
    weightGsm: 100,
    widthInches: inches(44),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.25),
    drapeClass: "LIGHT",
    costPerMeterMinor: 310_000,
    careInstructions: "Dry clean only.",
    drapeNotes: "Even sheen for evening depth.",
    garmentUse: "Evening kurtas, formal separates",
    lotMetres: 26,
    reorderMetres: 14,
  },
  {
    name: "Demo Wheat Herringbone",
    composition: "Wool-poly herringbone",
    file: "demo-wheat-herringbone.jpg",
    hex: "#D8CDB8",
    texture: "weave",
    weightGsm: 270,
    widthInches: inches(58),
    stretchPercent: 2,
    shrinkageAllowance: inches(0.3),
    drapeClass: "HEAVY",
    costPerMeterMinor: 198_000,
    careInstructions: "Dry clean preferred.",
    drapeNotes: "Broken twill for tailored structure.",
    garmentUse: "Blazers, waistcoats, coats",
    lotMetres: 41,
    reorderMetres: 22,
  },
  {
    name: "Demo Sky Cotton Voile",
    composition: "Cotton voile",
    file: "demo-sky-cotton-voile.jpg",
    hex: "#A8B6C4",
    texture: "sheer",
    weightGsm: 68,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.25),
    drapeClass: "LIGHT",
    costPerMeterMinor: 64_000,
    careInstructions: "Delicate wash; shade dry.",
    drapeNotes: "Cool tint for summer sets.",
    garmentUse: "Summer co-ords, dupattas",
    lotMetres: 103,
    reorderMetres: 30,
  },
  {
    name: "Demo Rose Modal",
    composition: "Modal jersey",
    file: "demo-rose-modal.jpg",
    hex: "#C4A09A",
    texture: "knit",
    weightGsm: 160,
    widthInches: inches(60),
    stretchPercent: 6,
    shrinkageAllowance: inches(0.2),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 98_000,
    careInstructions: "Cold wash; low heat tumble optional.",
    drapeNotes: "Silky knit drape for soft tops.",
    garmentUse: "Soft tops, lounge kurtas",
    lotMetres: 59,
    reorderMetres: 25,
  },
  {
    name: "Demo Ink Wool Gauze",
    composition: "Wool gauze",
    file: "demo-ink-wool-gauze.jpg",
    hex: "#2B2926",
    texture: "sheer",
    weightGsm: 180,
    widthInches: inches(54),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.4),
    drapeClass: "LIGHT",
    costPerMeterMinor: 175_000,
    careInstructions: "Dry clean or hand wash cold.",
    drapeNotes: "Open weave for layered wraps.",
    garmentUse: "Layered wraps, light coats",
    lotMetres: 33,
    reorderMetres: 18,
  },
  {
    name: "Demo Champagne Tissue",
    composition: "Silk tissue",
    file: "demo-champagne-tissue.jpg",
    hex: "#E5DCC8",
    texture: "sheer",
    weightGsm: 50,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.15),
    drapeClass: "LIGHT",
    costPerMeterMinor: 440_000,
    careInstructions: "Dry clean only; store rolled.",
    drapeNotes: "Fine shimmer for guest occasion.",
    garmentUse: "Dupattas, festive overlays",
    lotMetres: 19,
    reorderMetres: 12,
  },
  {
    name: "Demo Midnight Satin",
    composition: "Poly satin",
    file: "demo-midnight-satin.jpg",
    hex: "#16181D",
    texture: "silk",
    weightGsm: 125,
    widthInches: inches(44),
    stretchPercent: 0,
    shrinkageAllowance: inches(0.2),
    drapeClass: "MEDIUM",
    costPerMeterMinor: 115_000,
    careInstructions: "Cool iron; dry clean for best sheen.",
    drapeNotes: "Deep ground with controlled sheen.",
    garmentUse: "Evening separates, contrast panels",
    lotMetres: 36,
    reorderMetres: 16,
  },
];

/** PKR per metre → paisa (150–400 inclusive). */
export function launchFabricPriceMinor(index: number): number {
  const pkr = 150 + Math.round((index / 29) * 250);
  return Math.min(400, Math.max(150, pkr)) * 100;
}

/** Launch inventory — 30 spiral-drape catalogue fabrics at retail cost band. */
export const LAUNCH_FABRIC_CATALOG = DEMO_FABRIC_CATALOG.slice(0, 30).map(
  (def, index) => ({
    ...def,
    costPerMeterMinor: launchFabricPriceMinor(index),
  }),
);

for (const def of DEMO_FABRIC_CATALOG) {
  if (!def.name.startsWith("Demo")) {
    throw new Error(`Fabric name must start with Demo: ${def.name}`);
  }
}

export function metresToHundredths(metres: number): number {
  return Math.round(metres * 100);
}
